application: great-developer
version: 1
runtime: python
api_version: 1

# TEMP - DURING DEVELOPMENT ONLY!
#default_expiration: "1m"

handlers:
 - url: /js
   static_dir: js

 - url: /css
   static_dir: css

 - url: /cache.manifest
   mime_type: text/cache-manifest
   static_files: cache.manifest
   upload: cache.manifest

 - url: /images
   static_dir: images

 - url: /.*
   script: main.py
